Minor update after the review 1

diff --git a/lava-deployment-tool b/lava-deployment-tool
--- a/lava-deployment-tool
+++ b/lava-deployment-tool
@@ -104,8 +104,8 @@ LAVA_RABBIT_USER='$LAVA_RABBIT_USER'
 LAVA_RABBIT_PASSWORD='$LAVA_RABBIT_PASSWORD'
 # Scheduler configuration
 LAVA_SCHEDULER_ENABLED='$LAVA_SCHEDULER_ENABLED'
-LAVA_SERVER_IP='$LD_LAVA_SERVER_IP'
-LAVA_PROXY='$LD_LAVA_PROXY'
+LAVA_SERVER_IP='$LAVA_SERVER_IP'
+LAVA_PROXY='$LAVA_PROXY'
 INSTANCE_CONF
 }
 
@@ -306,10 +306,8 @@ install_fs() {
     # Static file cache
     mkdir -p $LAVA_PREFIX/$LAVA_INSTANCE/var/www/lava-server/static
     # Lava-dispatcher folders
-    mkdir -p $LAVA_PREFIX/$LAVA_INSTANCE/var/www/lava-server/images
     mkdir -p $LAVA_PREFIX/$LAVA_INSTANCE/var/www/lava-server/images/cache
     mkdir -p $LAVA_PREFIX/$LAVA_INSTANCE/var/www/lava-server/images/tmp
-    mkdir -p $LAVA_PREFIX/$LAVA_INSTANCE/var/www/lava-server/results
     # Repository of precious user-generated data (needs backup)
     mkdir -p $LAVA_PREFIX/$LAVA_INSTANCE/var/lib/lava-server/media
     # Celery state 
@@ -904,10 +902,10 @@ config_lava_dispatcher() {
 
     while true; do
 
-        read -p "Please enter the IP address: " LD_LAVA_SERVER_IP
+        read -p "Please enter the IP address: " LAVA_SERVER_IP
 
-        if test -n "$LD_LAVA_SERVER_IP" && echo "$LD_LAVA_SERVER_IP" | grep -q -E -e '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'; then
-            echo "The IP address is '$LD_LAVA_SERVER_IP'"
+        if test -n "$LAVA_SERVER_IP" && echo "$LAVA_SERVER_IP" | grep -q -E -e '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'; then
+            echo "The IP address is '$LAVA_SERVER_IP'"
             break
         else
             echo "Incorrect IP address"
@@ -920,47 +918,47 @@ config_lava_dispatcher() {
 
     echo "This is the address and port of cache proxy service, format is like:"
     echo "http://192.168.1.10:3128/"
-    read -p "Please enter the URL: " LD_LAVA_PROXY
+    read -p "Please enter the URL: " LAVA_PROXY
 
 
     # Location for rootfs/boot tarballs extracted from images
-    export LD_LAVA_IMAGE_TMPDIR=$LAVA_PREFIX/$LAVA_INSTANCE/var/www/lava-server/images/tmp
+    export LAVA_IMAGE_TMPDIR=$LAVA_PREFIX/$LAVA_INSTANCE/var/www/lava-server/images/tmp
 
     # URL where LAVA_IMAGE_TMPDIR can be accessed remotely
-    export LD_LAVA_IMAGE_URL=http://$LD_SERVER_IP/lava-server/images/tmp
+    export LAVA_IMAGE_URL=http://$SERVER_IP/lava-server/images/tmp
 
     # Location on the device for storing test results.
-    export LD_LAVA_RESULT_DIR=$LAVA_PREFIX/$LAVA_INSTANCE/var/www/lava-server/results
+    export LAVA_RESULT_DIR=$LAVA_PREFIX/$LAVA_INSTANCE/tmp
 
     # Location for caching downloaded artifacts such as hwpacks and images
-    export LD_LAVA_CACHEDIR=$LAVA_PREFIX/$LAVA_INSTANCE/var/www/lava-server/images/cache
+    export LAVA_CACHEDIR=$LAVA_PREFIX/$LAVA_INSTANCE/var/www/lava-server/images/cache
 
 }
 
 gen_lava_dispatcher_config() {
     LAVA_DISPATCHER_CONFIG_FILE=$LAVA_PREFIX/$LAVA_INSTANCE/etc/lava-dispatcher/lava-dispatcher.conf
 
-    echo "Creating lava-dispatcher config file %LAVA_DISPATCHER_CONFIG_FILE"
+    echo "Creating lava-dispatcher config file $LAVA_DISPATCHER_CONFIG_FILE"
     sudo sh -c "cat >$LAVA_DISPATCHER_CONFIG_FILE" <<LAVA_DISPATCHER_CONF
 # This file was automatically generated by lava-deployment-tool.sh
 
-LAVA_SERVER_IP = $LD_LAVA_SERVER_IP
+LAVA_SERVER_IP = $LAVA_SERVER_IP
 
 # Location for rootfs/boot tarballs extracted from images
-LAVA_IMAGE_TMPDIR = $LD_LAVA_IMAGE_TMPDIR
+LAVA_IMAGE_TMPDIR = $LAVA_IMAGE_TMPDIR
 
 # URL where LAVA_IMAGE_TMPDIR can be accessed remotely
 LAVA_IMAGE_URL = http://%(LAVA_SERVER_IP)s/images/tmp
 
 # Location on the device for storing test results.
-LAVA_RESULT_DIR = $LD_LAVA_RESULT_DIR
+LAVA_RESULT_DIR = $LAVA_RESULT_DIR
 
 # Location for caching downloaded artifacts such as hwpacks and images
-LAVA_CACHEDIR = $LD_LAVA_CACHEDIR
+LAVA_CACHEDIR = $LAVA_CACHEDIR
 
 # This is the address and port of cache proxy service, format is like:
 # LAVA_PROXY = http://192.168.1.10:3128/
-LAVA_PROXY = $LD_LAVA_PROXY
+LAVA_PROXY = $LAVA_PROXY
 
 LAVA_DISPATCHER_CONF
 
@@ -984,7 +982,7 @@ install_config_app() {
     lava-server manage \
         --instance-template=$LAVA_ROOT/instances/{instance}/etc/lava-server/{{filename}}.conf \
         --instance=$LAVA_INSTANCE \
-        build_static --noinput --link || die "Failed to update the cache of static content"
+        buistatic --noinput --link || die "Failed to update the cache of static content"
     set +x
 
     echo "Stopping instance for database changes..."
