Add cmd_bundle and the bundle command
This command allows one to create standalone 'bundles' of all the code
required to get lava instance up and running.

diff --git a/lava-deployment-tool b/lava-deployment-tool
--- a/lava-deployment-tool
+++ b/lava-deployment-tool
@@ -1525,6 +1525,30 @@ cmd_manage() {
 }
 
 
+cmd_bundle() {
+    LAVA_REQUIREMENT=${1:-requirements.txt}
+    LAVA_BUNDLE=${2:-lava.pybundle}
+    local step
+    for step in $LAVA_INSTALL_STEPS; do
+        defaults_$step
+    done
+    LAVA_FULL_REQUIREMENT=$(mktemp)
+    for step in $LAVA_INSTALL_STEPS; do
+        pkglist_$step >> "$LAVA_FULL_REQUIREMENT"
+    done
+    echo "The resulting file can be copied for off-line installation"
+    echo "Do you wnt to create $LAVA_BUNDLE with the following packages:"
+    echo
+    cat "$LAVA_FULL_REQUIREMENT"
+    echo
+    read -p "Type BUNDLE to continue: " RESPONSE
+    test "$RESPONSE" = 'BUNDLE' || return
+    set -x
+    pip bundle "$LAVA_BUNDLE" --timeout=30 --use-mirrors --requirement="$LAVA_FULL_REQUIREMENT" || die "Failed to create bundle"
+    set +x
+    rm -f "$LAVA_FULL_REQUIREMENT"
+}
+
 
 main() {
     os_check
@@ -1592,6 +1616,9 @@ main() {
             $cmd
             set +x
             set +e
+            ;;
+        bundle)
+            cmd_bundle "$@"
             ;;
         *)
             echo "Unknown command: $cmd, try help"
