be prepared to use either build_static or collectstatic command

diff --git a/lava-deployment-tool b/lava-deployment-tool
--- a/lava-deployment-tool
+++ b/lava-deployment-tool
@@ -1090,8 +1090,13 @@ install_config_app() {
         echo "Building cache of static files..."
         set -x
         rm -rf $LAVA_PREFIX/$LAVA_INSTANCE/var/www/lava-server/static
+        if lava-server manage | grep -q build_static; then
+            collectstatic_cmd=build_static
+        else
+            collectstatic_cmd="collectstatic -v0"
+        fi
         lava-server manage \
-            build_static --noinput --link || die "Failed to update the cache of static content"
+            $collectstatic_cmd --noinput --link || die "Failed to update the cache of static content"
         set +x
 
         echo "Stopping instance for database changes..."
